{"name": "test_auth_user", "status": "passed", "description": "This test successfuly authorise user by email and password", "steps": [{"name": "GET request to URL '/user/auth'", "status": "passed", "start": 1660232835203, "stop": 1660232835665}], "start": 1660232835203, "stop": 1660232835666, "uuid": "9d462686-b6dc-42e9-8e22-ece3a1fb7f08", "historyId": "7410e1ac45bbb4691d8287256f39af99", "testCaseId": "ce2a1413e204011ce5aea1bac6a45b93", "fullName": "tests.test_user_auth.TestUserAuth#test_auth_user", "labels": [{"name": "epic", "value": "Тесты на авторизацию"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "subSuite", "value": "TestUserAuth"}, {"name": "host", "value": "MacBook-Air-Irisa.local"}, {"name": "thread", "value": "90681-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "links": [{"type": "test_case", "url": "ID теста в системе управления тестированием", "name": "ID теста в системе управления тестированием"}, {"type": "issue", "url": "ID дефекта в баг-треккинговой системе", "name": "ID дефекта в баг-треккинговой системе"}, {"type": "link", "url": "Cсылка на какой-то внешний ресурс", "name": "Cсылка на какой-то внешний ресурс"}]}